refactored
ruslanbk11/smart-home-2019 pull request #1
Opened 2019-10-10 20:19 UTC by ruslanbk11

2019-10-16 20:47 UTC, iagoshkov requested changes
Исправляйте по комментариями

2019-10-16 20:47 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/HomeObject.java
> +public class HomeObject {
Плохая абстракция - конкретно сейчас совпало, что внутренее состояние двери и света представвлены одной boolean переменной.
Но так не будет всегда - у двери появится состояние замка - закрыт на ключ или нет, у света может повиться более сложное состояние - не просто on/off а сила света например, если это резисторный светильник. Ничего общего кроме id у них нет.

2019-10-16 20:47 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventRunner.java
> +    private static SensorEvent getNextSensorEvent() {
нарушен SRP - методы getNextSensorEvent и обработка событий никак не связаны. Решают разные задачи и имеют разные причины для изменений.
Исправьте.

2019-10-16 20:47 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventRunner.java
> +                case LIGHT_ON:
нарушен OCP - каждый раз при появлении нового типа события нам нужно будет "втыкать" в этот код новый case.

2019-10-16 20:47 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventRunner.java
> +            }
А куда делся случай, когда мы выключаем свет во всем доме при закрытии входной двери?

2019-10-16 20:47 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventRunner.java
> +    private static HomeObject checkObject(String eventId, Collection<Room> rooms, SensorEventType type){
логичнее было бы назвать метод findObject а не checkObject.
Почему этот метод находится в этом классе? нарушение SRP.
Исправьте.

2019-10-16 20:47 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventRunner.java
> +                case LIGHT_ON:
Исправьте - на прошлом занятии проговаривали как именно это делается.

2019-10-20 17:02 UTC, ruslanbk11 commented
@sbt-agoshkov, поправил, посмотрите, пожалуйста)

2019-10-22 21:29 UTC, a-ivanov requested changes
На правильном пути, но надо немного доделать. За юнит тесты - респект.

2019-10-22 21:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Reader.java
> +    SmartHome read(String fileName) throws IOException;
Leaky abstraction: детали имплементации видны в абстракции. Исправьте.

2019-10-22 21:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEvent.java
> +    static SensorEvent getNextSensorEvent() {
Нарушение SRP - класс хранит состояние и предоставляет новое событие (это отдельная responsibility). Исправьте.

2019-10-22 21:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventHandler.java
> +class HallDoorEventHandler {
Добавьте интерфейсы для всех *EventHandler'ов - это же абстракция, а классы для обработки разных событий - это имплементации.

2019-10-22 21:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventRunner.java
> +            }
HallDoorEventHandler.

2019-10-24 16:32 UTC, ruslanbk11 commented on src/main/java/ru/sbt/mipt/oop/Reader.java
> +    SmartHome read(String fileName) throws IOException;
Тут нужно убрать exception, или filename тоже?

2019-10-24 18:02 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Reader.java
> +    SmartHome read(String fileName) throws IOException;
И filename тоже

2019-10-26 19:44 UTC, a-ivanov requested changes
Уже лучше, поправьте немного.

2019-10-26 19:44 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventRunner.java
> +            }
Сразу не заметил: в этом классе нарушен OCP, при добавлении нового события придется менять текущий код с бизнес логикой. Исправьте.

2019-10-26 19:44 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandler.java
> +    static void handle(SensorEvent event, SmartHome smartHome){}
Почему метод статичный?

2019-10-26 19:45 UTC, a-ivanov commented
По первому дз комментарии исправлены в https://github.com/ruslanbk11/smart-home-2019/pull/2? Если да, то закройте этот рекест.

2019-11-10 08:40 UTC, merged