Hw3
ruslanbk11/smart-home-2019 pull request #3
Opened 2019-11-10 17:39 UTC by ruslanbk11

Добавил классы для сигнализации, обработку событий сигнализации, не очень понял, как передавать пароль для сигнализации вместе с event'ом. Декоратор и тесты чуть позже :)

2019-11-10 17:54 UTC, sbt-agoshkov commented
А что непонятного - нужно в ивенте сделать поле password.20:39, 10 ноября 2019 г., Ruslan Koshkin <notifications@github.com>:Добавил классы для сигнализации, обработку событий сигнализации, не очень понял, как передавать пароль для сигнализации вместе с event'ом. Декоратор и тесты чуть позже :)



You can view, comment on, or merge this pull request online at:
  https://github.com/ruslanbk11/smart-home-2019/pull/3

Commit Summary

  I added composite, right?
  Added composite, refactored tests
  Added alarm with states, new sensorEventTypes and AlarmEventHandler.


File Changes

  
    M
    smart-home-1.js
    (175)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/Action.java
    (5)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/Actionable.java
    (5)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/Application.java
    (16)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/Door.java
    (23)
  
  
    D
    src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
    (21)
  
  
    D
    src/main/java/ru/sbt/mipt/oop/EventHandler.java
    (5)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/EventRunner.java
    (23)
  
  
    D
    src/main/java/ru/sbt/mipt/oop/HallDoorEventHandler.java
    (22)
  
  
    D
    src/main/java/ru/sbt/mipt/oop/HallDoorEventHandlerTest.java
    (29)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
    (24)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/Light.java
    (23)
  
  
    D
    src/main/java/ru/sbt/mipt/oop/LightEventHandler.java
    (21)
  
  
    D
    src/main/java/ru/sbt/mipt/oop/Reader.java
    (5)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/Room.java
    (21)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/SensorEvent.java
    (4)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/SensorEventGetter.java
    (2)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/SensorEventType.java
    (7)
  
  
    M
    src/main/java/ru/sbt/mipt/oop/SmartHome.java
    (15)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/alarm/ActivatedState.java
    (30)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/alarm/Alarm.java
    (38)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/alarm/AlarmState.java
    (7)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/alarm/AlertState.java
    (29)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/alarm/DeactivatedState.java
    (27)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/eventHandlers/AlarmEventHandler.java
    (41)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/eventHandlers/DoorEventHandler.java
    (41)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/eventHandlers/EventHandler.java
    (7)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/eventHandlers/HallDoorEventHandler.java
    (46)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/eventHandlers/LightEventHandler.java
    (43)
  
  
    R
    src/main/java/ru/sbt/mipt/oop/readers/JsonReader.java
    (3)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/readers/Reader.java
    (7)
  
  
    R
    src/main/java/ru/sbt/mipt/oop/tests/DoorEventHandlerTest.java
    (34)
  
  
    A
    src/main/java/ru/sbt/mipt/oop/tests/HallDoorEventHandlerTest.java
    (43)
  
  
    R
    src/main/java/ru/sbt/mipt/oop/tests/LightEventHandlerTest.java
    (37)
  


Patch Links:

  https://github.com/ruslanbk11/smart-home-2019/pull/3.patch
  https://github.com/ruslanbk11/smart-home-2019/pull/3.diff


—You are receiving this because your review was requested.Reply to this email directly, view it on GitHub, or unsubscribe.

Илья

2019-11-12 14:37 UTC, a-ivanov requested changes

2019-11-12 14:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/DeactivatedState.java
> +        if (alarm.checkCode(code)) {
Здесь не нужно проверять код - как с сейфом в отеле сначала задается код и его не надо проверять.

2019-11-12 14:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/tests/AlarmTest.java
> +    static void setUp() {
А что этот тест тестирует?

2019-11-12 14:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        eventHandlers.add(new LightEventHandler(smartHome));
По заданию здесь еще должен быть декоратор для остановки обработки событий при тревожном состоянии.

2019-11-17 22:58 UTC, a-ivanov requested changes

2019-11-17 22:58 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventHandlers/AlarmDecorator.java
> +            for (EventHandler eventHandler : eventHandlers) {
Нарушение SRP - цепочка обработчиков вызывается отдельным классом. По заданию надо применить шаблон декоратор, он не сделан.

2019-11-21 13:49 UTC, ruslanbk11 commented
Если и сейчас неправильно, то я вообще ничего не понимаю ))

2019-11-25 08:54 UTC, a-ivanov requested changes

2019-11-25 08:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        eventHandlers.add(new AlarmDecorator(smartHome.alarm, new LightEventHandler(smartHome)));
Сейчас подход к декоратору правильный. Но на каждое событие != ALRAM_EVENT в каждом декораторе будет отправляться по 1 смс. Необходимо сделать так, чтобы отправлялось 1 смс на событие.

2019-11-30 11:51 UTC, ruslanbk11 commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        eventHandlers.add(new AlarmDecorator(smartHome.alarm, new LightEventHandler(smartHome)));
А чем тогда не подошло предыдущее решение не подошло? Там ведь просто декоратор оборачивал все хэнлеры сразу и отправлялась одна смска

2019-12-02 12:54 UTC, a-ivanov requested changes

2019-12-02 12:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmDecorator.java
> +        this.runEvents(SensorEventGetter.getNextSensorEvent());
Это нарушение SRP, обработчик только обрабатывает события, итерация - отдельная ответственность.

2019-12-02 12:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmDecorator.java
> +            if (event.getType() == ALARM_DEACTIVATE) {
Строки 29-31 и 37-39 - дублируют друг друга, можно переписать так, чтобы не повторяться (DRY принцип)?

2019-12-12 14:36 UTC, a-ivanov approved these changes

2019-12-12 14:54 UTC, merged